#! /bin/sh

sxhkd &
tw quit 2>/dev/null
tw daemon &
wmname LG3D

#bspc monitor -d III IV V VI VII VIII IX X
#bspc monitor -d 0 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color \#333333
bspc config active_border_color \#333333
bspc config focused_border_color \#25467a

#bspc rule -a taskwm-picker desktop=tasks state=floating
#bspc rule -a taskwm-bar desktop=active state=floating sticky=on layer=above
bspc rule -a Taskwm-picker desktop=tasks state=tiled
bspc rule -a Taskwm-bar desktop=active state=floating sticky=on layer=above
bspc config focus_follows_pointer true

polybar top&
feh --bg-scale ~/Downloads/wallpaper2.jpg &
